apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fl-clients
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sumingsu40/FL-k3s-gitops.git
    targetRevision: main
    path: manifests/clients
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: fl-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
