apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fl-client-jetson
  namespace: fl-system
spec:
  selector:
    matchLabels:
      app: fl-client
      device: jetson
  template:
    metadata:
      labels:
        app: fl-client
        device: jetson
    spec:
      nodeSelector:
        device: jetson
      runtimeClassName: nvidia
      containers:
        - name: fl-client
          image: unknowming/fl-client-orin:v2.2
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
          args:
            - "-cid"
            - "0"
            - "-d"
            - "cuda"
            - "-su"
            - "fl-server.fl-system.svc.cluster.local:3000"
