apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-client-jetson03
  namespace: fl-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fl-client
      node: jetson03
  template:
    metadata:
      labels:
        app: fl-client
        node: jetson03
    spec:
      nodeName: jetson03
      runtimeClassName: nvidia
      containers:
        - name: fl-client
          image: unknowming/fl-client-jetson
          env:
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
          args:
            - "-cid"
            - "0"
            - "-d"
            - "cuda"
            - "-su"
            - "fl-server.fl-system.svc.cluster.local:3000"
