apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fl-client-jetson01
  namespace: fl-system
spec:
  selector:
    matchLabels:
      app: fl-client
      device: jetson01
  template:
    metadata:
      labels:
        app: fl-client
        device: jetson01
    spec:
      nodeSelector:
        device: jetson01
      runtimeClassName: nvidia
      containers:
        - name: fl-client
          image: unknowming/fl-client-jetson:v2.3
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: DEVICE
              value: "cuda"
            - name: NVIDIA_VISIBLE_DEVICES
              value: "all"
            - name: NVIDIA_DRIVER_CAPABILITIES
              value: "all"
          command: ["/bin/sh", "/etc/fl-client-id/entrypoint.sh"]
          volumeMounts:
            - name: fl-client-id
              mountPath: /etc/fl-client-id
      volumes:
        - name: fl-client-id
          configMap:
            name: fl-client-id-map
            defaultMode: 0555
